"""empty message

Revision ID: 642e3da6c798
Revises: b802f75c7840
Create Date: 2022-10-13 04:20:44.077148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642e3da6c798'
down_revision = 'b802f75c7840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('gender', sa.String(length=120), nullable=False))
    op.add_column('characters', sa.Column('hair_color', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'hair_color')
    op.drop_column('characters', 'gender')
    # ### end Alembic commands ###
